### ISSUE TITLE
New items not appearing

### ISSUE THREAD

**Issue by Ganondood** [Tonic-Box/D3Studio#1]
Hello im on the switch version, newest patch, and the following items wont show up in game while using d3studio, even the mephisto wings dont show when set in the visuals tab, wrong item id's?

Items not appearing in game:
Wanderer's Boots
Hatred's Grasp (Wings)
Mephisto (pet)
Guise of the Wanderer (TMog Plan)

Items that DO appear in game but do not register account wide when 'learning/binding' them:
Terror Unleashed (Wings)
The Dark Murglrr (Pet)
Dark Wanderer (Frame)

**Comment by Tonic-Box** [comment]
Yes thats because they are technically pc only. Some comebin, some dont, and wthevones that do its not that they dont bind. Its that when you hop out it poofs them because it checks andcrealizes that the liscence bits for the blizcon pack arent set. Not much to do about it till we find out the correct liscenve bit numbers to set.

Similar to how the necro preorder thing works.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by Ganondood** [comment]
I see, interesting, it's weird how some blizzcon stuf shows as an actual item like Visage of the Betrayer (illidian helm) but the wings of the betrayer only show up when set in the visual tab, not as an item. You would think the mephisto wings and pet would show up too in the visual tab so and upon loggin in gamme at character select, but they are invis :[

**Comment by Tonic-Box** [comment]
Mmm yes and no. If you want a more thurough explenation though or want to learn more you can feel free to shoot me an email or (better yet) add me on discord. :)

Email: gsec.tonicbox@protonmail.com
Discord: TonicBox#5422

Sent from ProtonMail mobile

-------- Original Message --------
